const MONGODB_URL = "mongodb://127.0.0.1:27017/miguelangel2345";
const FRONTEND_URL = "http://localhost:3010";
const BACKEND_URL = "http://localhost:5000";
const SECRET = "miguelangel2345";
const EXPIRESTIME = "2h";
const EXPIRESFOREVERTIME = "365d";

const VERIFICATION_MAIL_ADDRESS = "rayanbrooks102@gmail.com";
const VERIFICATION_MAIL_PASSWORD = "vmsmxagtzqddmvtw";

const TWITCH_TOKEN_URL = "https://id.twitch.tv/oauth2/token";
const TWITCH_USER_URL = "https://api.twitch.tv/helix/users";
const TWITCH_CLIENT_ID = "rxxe7g6k46ychf0q9oinm19f7a0paj";
const TWITCH_CLIENT_SECRET = "xyt6fiybcsftp9brvow63rem2jpite";
const TWITCH_REDIRECT_URI = `${FRONTEND_URL}/profile`;

const STREAMELEMENTS_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpVCJ9.eyJpc3MiOiJjaXRhZGVsIiwiZXhwIjoxNzAzNTU0Mjg2LCJqdGkiOiIwYWFhNjA1Yi0zOWY4LTRkOTctOTg3ZC1jZDZhN2IwZTc3NTQiLCJjaGFubmVsIjoiNjU2MjlmZWVhYjcyYmVhNTY0NGFhMTJmIiwicm9sZSI6Im93bmVyIiwiYXV0aFRva2VuIjoiZXhUbFJNT1B1Zktfa0FsWDU0RnpNdWlOYnhkNnlJMjZ5MDhQZmdFVng5SzBEaEZIIiwidXNlciI6IjY1NjI5ZmVlYWI3MmJlYTU2NDRhYTEyZSIsInVzZXJfaWQiOiJhNjBjNjU5ZS0zMzIwLTRkYzMtYjUyZi0zZGZhZjUxZDk0MGIiLCJ1c2VyX3JvbGUiOiJjcmVhdG9yIiwicHJvdmlkZXIiOiJ0d2l0Y2giLCJwcm92aWRlcl9pZCI6Ijk4NzA2NjExNiIsImNoYW5uZWxfaWQiOiJlNjY1NjFmNi0zZTE5LTQ5N2MtYmQwNS1mOGRlMmU3MWQ4YTAiLCJjcmVhdG9yX2lkIjoiOTZkNDIyYTAtMzcxNS00OTgzLWExYzgtNmRlNmY3YzFiMDNhIn0.pUUFIvBIAcd9YcHpMycm6GPMdRR-o6MovFCP5JAFEMs';
const STREAMELEMENTS_CHANNEL_ID = '5c980c4e2f860942cf9093b7';
const STREAMELEMENTS_GET_INFO_URL = 'https://api.streamelements.com/kappa/v2/points';

export default {
  MONGODB_URL,
  FRONTEND_URL,
  BACKEND_URL,
  SECRET,
  EXPIRESTIME,
  EXPIRESFOREVERTIME,
  VERIFICATION_MAIL_ADDRESS,
  VERIFICATION_MAIL_PASSWORD,
  TWITCH_TOKEN_URL,
  TWITCH_CLIENT_ID,
  TWITCH_CLIENT_SECRET,
  TWITCH_REDIRECT_URI,
  TWITCH_USER_URL,
  STREAMELEMENTS_TOKEN,
  STREAMELEMENTS_CHANNEL_ID,
  STREAMELEMENTS_GET_INFO_URL
};
